Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.hostname = "node1"
    node1.vm.network "public_network", ip: "172.20.10.2", bridge: "en0: Wi-Fi (Wireless)"
    node1.vm.network "forwarded_port", guest: 50070, host: 50070, guest_ip: "172.20.10.2"
    node1.vm.network "forwarded_port", guest: 8088, host: 8088
    node1.vm.network "forwarded_port", guest: 19888, host: 19888
    node1.vm.synced_folder ".", "/vagrant", type: "rsync"
  end

  (2..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "node#{i}"
      node.vm.network "public_network", ip: "172.20.10.#{i+1}", bridge: "en0: Wi-Fi (Wireless)"
      node.vm.synced_folder ".", "/vagrant", type: "rsync"
    end
  end
end
