Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "node#{i}"
      node.vm.network "public_network", ip: "192.168.1.#{i}0", bridge: "en0: Wi-Fi (Wireless)"
      node.vm.synced_folder ".", "/vagrant", type: "rsync"
    end
  end
end
